### ISSUE TITLE
AssertionError: Box regression deltas become infinite or NaN!

### ISSUE THREAD

**Issue by zzzzjx** [MegviiDetection/FSCE#47]
I meet this exception when I run the command “CUDA_VISIBLE_DEVICES=0,1 python3 -m tools.train_net --num-gpus 2  --config-file /home/sjk/ZJX/FSCE/configs/COCO/R-101/base_training.yml”  ，the IMS_PER_BATCH is set to 32  BASE_LR is set to 0.02. All discriptions are :
Traceback (most recent call last):
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sjk/ZJX/FSCE/tools/train_net.py", line 132, in <module>
    args=(args,),
  File "/home/sjk/ZJX/FSCE/fsdet/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/sjk/ZJX/FSCE/fsdet/engine/launch.py", line 84, in _distributed_worker
    main_func(*args)
  File "/home/sjk/ZJX/FSCE/tools/train_net.py", line 119, in main
    return trainer.train()
  File "/home/sjk/ZJX/FSCE/fsdet/engine/defaults.py", line 397, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/sjk/ZJX/FSCE/fsdet/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/sjk/ZJX/FSCE/fsdet/engine/train_loop.py", line 212, in run_step
    loss_dict = self.model(data)
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sjk/ZJX/FSCE/fsdet/modeling/meta_arch/rcnn.py", line 148, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/sjk/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sjk/ZJX/FSCE/fsdet/modeling/proposal_generator/rpn.py", line 176, in forward
    outputs.predict_proposals(),  # transform anchors to proposals by applying delta
  File "/home/sjk/ZJX/FSCE/fsdet/modeling/proposal_generator/rpn_outputs.py", line 419, in predict_proposals
    pred_anchor_deltas_i, anchors_i.tensor
  File "/home/sjk/ZJX/FSCE/fsdet/modeling/box_regression.py", line 79, in apply_deltas
    assert torch.isfinite(deltas).all().item(), "Box regression deltas become infinite or NaN!"
AssertionError: Box regression deltas become infinite or NaN!

**Comment by hetao828** [comment]
Have you solved this problem? I also meet, but I don't how to solve and why this happens?

**Comment by 1740533374** [comment]
Have you solved this problem? I also meet, but I don't how to solve and why this happens?
