### ISSUE TITLE
prepare dataset error

### ISSUE THREAD

**Issue by ghost** [MegviiDetection/FSCE#59]
# prepare_coco_few_shot.py
作者应该看得懂中文吧！！！
我跑标题的文件做数据集时，提示这个错误：
```python
File "prepare_coco_few_shot.py", line 17, in generate_seeds
    data = json.load(open(data_path))
IsADirectoryError: [Errno 21] Is a directory: 'datasets/cocosplit/datasplit/trainvalno5k.json'
```

然后我看源代码里面设置了一个这个json文件的路径后就直接load了，但是没这个文件啊？？？？我该怎么生成这个文件呢？

**Comment by ghost** [comment]
oh我在这个[网页](http://dl.yf.io/fs-det/datasets/cocosplit/datasplit/trainvalno5k.json)找到了，然后用wget下载了下来...

**Comment by jiaoxue52** [comment]
> oh我在这个[网页](http://dl.yf.io/fs-det/datasets/cocosplit/datasplit/trainvalno5k.json)找到了，然后用wget下载了下来...
哈喽，我在跑python setup.py build develop 这句话的时候，有个这样的报错，不知道您是否遇到，或者有什么修改建议吗？
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    package_data={"fsdet.model_zoo": get_model_zoo_configs()},
  File "setup.py", line 80, in get_model_zoo_configs
    shutil.rmtree(destination)
  File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 631, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 627, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
NotADirectoryError: [Errno 20] Not a directory: '/home/usst/huyu/FSCE-main/fsdet/model_zoo/configs'
期待您的回复，感谢。

**Comment by ghost** [comment]
> 

没遇到......

**Comment by jiaoxue52** [comment]
> > 
> 
> 没遇到......

好的，谢谢你的回复

**Comment by 2563895797** [comment]
> > oh我在这个[网页](http://dl.yf.io/fs-det/datasets/cocosplit/datasplit/trainvalno5k.json)找到了，然后用wget下载了下来...
> > 哈喽，我在跑python setup.py build develop 这句话的时候，有个这样的报错，不知道您是否遇到，或者有什么修改建议吗？
> > Traceback (most recent call last):
> > File "setup.py", line 99, in 
> > package_data={"fsdet.model_zoo": get_model_zoo_configs()},
> > File "setup.py", line 80, in get_model_zoo_configs
> > shutil.rmtree(destination)
> > File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 718, in rmtree
> > _rmtree_safe_fd(fd, path, onerror)
> > File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 631, in _rmtree_safe_fd
> > onerror(os.scandir, path, sys.exc_info())
> > File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 627, in _rmtree_safe_fd
> > with os.scandir(topfd) as scandir_it:
> > NotADirectoryError: [Errno 20] Not a directory: '/home/usst/huyu/FSCE-main/fsdet/model_zoo/configs'
> > 期待您的回复，感谢。

这个在别的issue有的，你把configs直接删了，再跑一遍试试

**Comment by jiaoxue52** [comment]
> > > oh我在这个[网页](http://dl.yf.io/fs-det/datasets/cocosplit/datasplit/trainvalno5k.json)找到了，然后用wget下载了下来...
> > > 哈喽，我在跑python setup.py build develop 这句话的时候，有个这样的报错，不知道您是否遇到，或者有什么修改建议吗？
> > > Traceback (most recent call last):
> > > File "setup.py", line 99, in
> > > package_data={"fsdet.model_zoo": get_model_zoo_configs()},
> > > File "setup.py", line 80, in get_model_zoo_configs
> > > shutil.rmtree(destination)
> > > File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 718, in rmtree
> > > _rmtree_safe_fd(fd, path, onerror)
> > > File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 631, in _rmtree_safe_fd
> > > onerror(os.scandir, path, sys.exc_info())
> > > File "/home/anaconda/miniconda3/envs/fsce/lib/python3.8/shutil.py", line 627, in _rmtree_safe_fd
> > > with os.scandir(topfd) as scandir_it:
> > > NotADirectoryError: [Errno 20] Not a directory: '/home/usst/huyu/FSCE-main/fsdet/model_zoo/configs'
> > > 期待您的回复，感谢。
> 
> 这个在别的issue有的，你把configs直接删了，再跑一遍试试

好的，我会尝试一下，谢谢
